### ISSUE TITLE
universe performance question

### ISSUE THREAD

**Issue by christophe-g** [Hypercubed/Project-Chi#4]
Hey, 

Just wondering - as I am starting to delve into universe. 
I see a pretty long lag before anything renders on the [universe example](http://hypercubed.github.io/Project-Chi/#/examples/universe) - do you know if it is due to universe performance itself (the square example - with almost the same anount of data is much faster) or related to anything else ?

Thanks anyway for this example - I was almost quitting my try on universe before seeing this. 
I 'll try to convert it to vanilla js + polymer as a starter

Cheers,
C.

**Comment by Hypercubed** [comment]
Hi, sorry I missed this issue somehow.

The delay in rendering is likely due to Project-X not universe.  The data is loaded and processed before the page is rendered.  Then the data is fed to angular ui-grid, which can be pretty slow to render.  VanillaJS is likely much faster to first render... which I think you have already figured out.
